### ISSUE TITLE
Refactor Phylogenetics

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/OrthoEvolution#154]
##### What are you trying to accomplish?

Improve the Phylogenetics API and code style.

##### What is the error or issue?

The code is not using a number of Python's best practices.

##### TODO

- [ ] Refactor `ETE3PAML`
- [ ] Refactor `PhyML`
- [ ] Remove pexpect from `Phylip` in favor of subprocess
- [ ] Consider deprecating `PhyloTree`

**Comment by sdhutchins** [comment]
@grabear I think I can have this done by Friday - I know we were wanting to do documentation after you got #152 done, but I feel confident I can knock this out close that point.

**Comment by sdhutchins** [comment]
Fixed in #212
